package_group(
    name = "specific_version",
    packages = ["//experimental/users/chungha/androidbootcamp/java/com/google/android/bootcamp/memegen/lib"],
)

package(default_visibility = [":specific_version"])

licenses(["notice"])  # Apache 2.0

exports_files(["LICENSE"])

android_library(
    name = "boilerpipe",
    srcs = ["boilerpipe-1.2.0.jar", "nekohtml-1.9.13.jar", "xerces-2.9.1.jar"],
)
